spring.application.name=user-service
# ===============================
# APPLICATION CONFIG
# ===============================
server.port=8082
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true


jwt.secret=o9vvMvAr7Y0HxejZ7PsYRfiF3ViktFc7aNECa3AEexD8JHbsvSTwR6dH7vFJrJvVl3GLOPJ9eoSgavK7ciawsQ==
jwt.expiration=3600000
eureka.client.service-url.defaultZone=
http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true