spring.application.name=driver-service

server.port=8086

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/rapido_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Logging
logging.pattern.level=%5p [${spring.application.name:},%X{X-Correlation-ID}]

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always