spring.application.name=ride-service

server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/rapido_db
spring.datasource.username=rapido_db
spring.datasource.password=Uttej123$

# JPA
spring.jpa.hibernate.ddl-auto=update

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672

# Eureka
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

# Logging
logging.pattern.level=%5p [${spring.application.name:},%X{X-Correlation-ID}]

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always