name: Rapido CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify Project Structure
        run: |
          pwd
          ls
          find . -name "pom.xml"

      - name: Build Application
        working-directory: rapido-clone-backend/rapido-clone-backend
        run: mvn clean package -DskipTests

      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "rapido-clone-backend/rapido-clone-backend/*"
          target: "/home/${{ secrets.EC2_USERNAME }}/Rapido-clone/rapido-clone-backend"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Rapido-clone/rapido-clone-backend

            docker compose down || true

            docker compose up --build -d

            docker system prune -f

            docker ps